// Auto-generated by Supabase MCP (`generate_typescript_types`).
// Re-run via the Supabase MCP `generate_typescript_types` tool whenever
// the schema changes. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      addresses: {
        Row: {
          city: string
          country: string
          county: string
          customer_id: string
          id: string
          is_default: boolean
          kind: Database["public"]["Enums"]["address_kind_t"]
          line1: string
          line2: string | null
          zip: string | null
        }
        Insert: {
          city: string
          country?: string
          county: string
          customer_id: string
          id?: string
          is_default?: boolean
          kind: Database["public"]["Enums"]["address_kind_t"]
          line1: string
          line2?: string | null
          zip?: string | null
        }
        Update: {
          city?: string
          country?: string
          county?: string
          customer_id?: string
          id?: string
          is_default?: boolean
          kind?: Database["public"]["Enums"]["address_kind_t"]
          line1?: string
          line2?: string | null
          zip?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "addresses_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      age_verifications: {
        Row: {
          id: string
          ip: unknown
          user_agent: string | null
          verified_at: string
        }
        Insert: {
          id?: string
          ip?: unknown
          user_agent?: string | null
          verified_at?: string
        }
        Update: {
          id?: string
          ip?: unknown
          user_agent?: string | null
          verified_at?: string
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          action: string
          actor: string | null
          after: Json | null
          at: string
          before: Json | null
          entity: string
          entity_id: string | null
          id: string
        }
        Insert: {
          action: string
          actor?: string | null
          after?: Json | null
          at?: string
          before?: Json | null
          entity: string
          entity_id?: string | null
          id?: string
        }
        Update: {
          action?: string
          actor?: string | null
          after?: Json | null
          at?: string
          before?: Json | null
          entity?: string
          entity_id?: string | null
          id?: string
        }
        Relationships: []
      }
      billing_profiles: {
        Row: {
          cnp: string | null
          company: string | null
          cui: string | null
          customer_id: string
          hq_address: string | null
          iban: string | null
          id: string
          reg_no: string | null
          type: Database["public"]["Enums"]["bill_type_t"]
        }
        Insert: {
          cnp?: string | null
          company?: string | null
          cui?: string | null
          customer_id: string
          hq_address?: string | null
          iban?: string | null
          id?: string
          reg_no?: string | null
          type: Database["public"]["Enums"]["bill_type_t"]
        }
        Update: {
          cnp?: string | null
          company?: string | null
          cui?: string | null
          customer_id?: string
          hq_address?: string | null
          iban?: string | null
          id?: string
          reg_no?: string | null
          type?: Database["public"]["Enums"]["bill_type_t"]
        }
        Relationships: [
          {
            foreignKeyName: "billing_profiles_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      coupons: {
        Row: {
          active: boolean
          code: string
          created_at: string
          expires_at: string | null
          fixed_off_cents: number | null
          id: string
          max_uses: number | null
          min_amount_cents: number
          percent_off: number | null
          used_count: number
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          expires_at?: string | null
          fixed_off_cents?: number | null
          id?: string
          max_uses?: number | null
          min_amount_cents?: number
          percent_off?: number | null
          used_count?: number
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          expires_at?: string | null
          fixed_off_cents?: number | null
          id?: string
          max_uses?: number | null
          min_amount_cents?: number
          percent_off?: number | null
          used_count?: number
        }
        Relationships: []
      }
      customers: {
        Row: {
          created_at: string
          email: string
          id: string
          marketing_opt_in: boolean
          name: string | null
          phone: string | null
          supabase_user_id: string | null
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          marketing_opt_in?: boolean
          name?: string | null
          phone?: string | null
          supabase_user_id?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          marketing_opt_in?: boolean
          name?: string | null
          phone?: string | null
          supabase_user_id?: string | null
        }
        Relationships: []
      }
      newsletter_subs: {
        Row: {
          consent_at: string
          email: string
          id: string
          unsubscribed_at: string | null
        }
        Insert: {
          consent_at?: string
          email: string
          id?: string
          unsubscribed_at?: string | null
        }
        Update: {
          consent_at?: string
          email?: string
          id?: string
          unsubscribed_at?: string | null
        }
        Relationships: []
      }
      order_counters: {
        Row: { last_seq: number; year: number }
        Insert: { last_seq?: number; year: number }
        Update: { last_seq?: number; year?: number }
        Relationships: []
      }
      order_events: {
        Row: {
          created_at: string
          id: string
          order_id: string
          payload: Json | null
          type: string
        }
        Insert: {
          created_at?: string
          id?: string
          order_id: string
          payload?: Json | null
          type: string
        }
        Update: {
          created_at?: string
          id?: string
          order_id?: string
          payload?: Json | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_events_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          code_snapshot: string
          id: string
          name_snapshot: string
          order_id: string
          product_id: string
          qty: number
          unit_price_cents: number
        }
        Insert: {
          code_snapshot: string
          id?: string
          name_snapshot: string
          order_id: string
          product_id: string
          qty: number
          unit_price_cents: number
        }
        Update: {
          code_snapshot?: string
          id?: string
          name_snapshot?: string
          order_id?: string
          product_id?: string
          qty?: number
          unit_price_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          awb_number: string | null
          billing: Json | null
          created_at: string
          customer_id: string | null
          delivered_at: string | null
          discount_cents: number
          guest_email: string | null
          id: string
          idempotency_key: string | null
          notes: string | null
          order_number: string
          paid_at: string | null
          payment_method: Database["public"]["Enums"]["pay_method_t"]
          payment_status: Database["public"]["Enums"]["pay_status_t"]
          shipped_at: string | null
          shipping_address: Json | null
          shipping_cents: number
          shipping_method: Database["public"]["Enums"]["ship_method_t"]
          smartbill_invoice_id: string | null
          status: Database["public"]["Enums"]["order_status_t"]
          stripe_payment_intent: string | null
          stripe_session_id: string | null
          subtotal_cents: number
          total_cents: number
        }
        Insert: {
          awb_number?: string | null
          billing?: Json | null
          created_at?: string
          customer_id?: string | null
          delivered_at?: string | null
          discount_cents?: number
          guest_email?: string | null
          id?: string
          idempotency_key?: string | null
          notes?: string | null
          order_number: string
          paid_at?: string | null
          payment_method: Database["public"]["Enums"]["pay_method_t"]
          payment_status?: Database["public"]["Enums"]["pay_status_t"]
          shipped_at?: string | null
          shipping_address?: Json | null
          shipping_cents?: number
          shipping_method: Database["public"]["Enums"]["ship_method_t"]
          smartbill_invoice_id?: string | null
          status?: Database["public"]["Enums"]["order_status_t"]
          stripe_payment_intent?: string | null
          stripe_session_id?: string | null
          subtotal_cents: number
          total_cents: number
        }
        Update: {
          awb_number?: string | null
          billing?: Json | null
          created_at?: string
          customer_id?: string | null
          delivered_at?: string | null
          discount_cents?: number
          guest_email?: string | null
          id?: string
          idempotency_key?: string | null
          notes?: string | null
          order_number?: string
          paid_at?: string | null
          payment_method?: Database["public"]["Enums"]["pay_method_t"]
          payment_status?: Database["public"]["Enums"]["pay_status_t"]
          shipped_at?: string | null
          shipping_address?: Json | null
          shipping_cents?: number
          shipping_method?: Database["public"]["Enums"]["ship_method_t"]
          smartbill_invoice_id?: string | null
          status?: Database["public"]["Enums"]["order_status_t"]
          stripe_payment_intent?: string | null
          stripe_session_id?: string | null
          subtotal_cents?: number
          total_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      processed_events: {
        Row: { event_id: string; processed_at: string; source: string }
        Insert: { event_id: string; processed_at?: string; source: string }
        Update: { event_id?: string; processed_at?: string; source?: string }
        Relationships: []
      }
      product_images: {
        Row: {
          alt: string | null
          id: string
          product_id: string
          sort_order: number
          url: string
        }
        Insert: {
          alt?: string | null
          id?: string
          product_id: string
          sort_order?: number
          url: string
        }
        Update: {
          alt?: string | null
          id?: string
          product_id?: string
          sort_order?: number
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          abv: number
          active: boolean
          age_note: string | null
          bottle_color: Database["public"]["Enums"]["bottle_color_t"]
          code: string
          created_at: string
          decant: string | null
          gama: Database["public"]["Enums"]["gama_t"]
          glass: string | null
          grape: string | null
          hero_image: string | null
          id: string
          name: string
          notes: string | null
          pair: string | null
          price_cents: number
          serving_temp: string | null
          short: string | null
          slug: string
          stock: number
          sweetness: Database["public"]["Enums"]["sweetness_t"]
          taste: string | null
          type: Database["public"]["Enums"]["wine_type_t"]
          updated_at: string
          year: number | null
        }
        Insert: {
          abv: number
          active?: boolean
          age_note?: string | null
          bottle_color: Database["public"]["Enums"]["bottle_color_t"]
          code: string
          created_at?: string
          decant?: string | null
          gama: Database["public"]["Enums"]["gama_t"]
          glass?: string | null
          grape?: string | null
          hero_image?: string | null
          id?: string
          name: string
          notes?: string | null
          pair?: string | null
          price_cents: number
          serving_temp?: string | null
          short?: string | null
          slug: string
          stock?: number
          sweetness: Database["public"]["Enums"]["sweetness_t"]
          taste?: string | null
          type: Database["public"]["Enums"]["wine_type_t"]
          updated_at?: string
          year?: number | null
        }
        Update: {
          abv?: number
          active?: boolean
          age_note?: string | null
          bottle_color?: Database["public"]["Enums"]["bottle_color_t"]
          code?: string
          created_at?: string
          decant?: string | null
          gama?: Database["public"]["Enums"]["gama_t"]
          glass?: string | null
          grape?: string | null
          hero_image?: string | null
          id?: string
          name?: string
          notes?: string | null
          pair?: string | null
          price_cents?: number
          serving_temp?: string | null
          short?: string | null
          slug?: string
          stock?: number
          sweetness?: Database["public"]["Enums"]["sweetness_t"]
          taste?: string | null
          type?: Database["public"]["Enums"]["wine_type_t"]
          updated_at?: string
          year?: number | null
        }
        Relationships: []
      }
      return_counters: {
        Row: { seq: number; year: number }
        Insert: { seq?: number; year: number }
        Update: { seq?: number; year?: number }
        Relationships: []
      }
      return_items: {
        Row: {
          id: string
          order_item_id: string
          product_code: string
          product_name: string
          qty: number
          return_id: string
          unit_price_cents: number
        }
        Insert: {
          id?: string
          order_item_id: string
          product_code: string
          product_name: string
          qty: number
          return_id: string
          unit_price_cents: number
        }
        Update: {
          id?: string
          order_item_id?: string
          product_code?: string
          product_name?: string
          qty?: number
          return_id?: string
          unit_price_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "return_items_order_item_id_fkey"
            columns: ["order_item_id"]
            isOneToOne: false
            referencedRelation: "order_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "return_items_return_id_fkey"
            columns: ["return_id"]
            isOneToOne: false
            referencedRelation: "returns"
            referencedColumns: ["id"]
          },
        ]
      }
      returns: {
        Row: {
          created_at: string
          customer_id: string
          iban: string | null
          id: string
          order_id: string
          product_state: Database["public"]["Enums"]["return_product_state"]
          reason: string | null
          resolution: Database["public"]["Enums"]["return_resolution"]
          return_number: string
          status: Database["public"]["Enums"]["return_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          customer_id: string
          iban?: string | null
          id?: string
          order_id: string
          product_state: Database["public"]["Enums"]["return_product_state"]
          reason?: string | null
          resolution: Database["public"]["Enums"]["return_resolution"]
          return_number: string
          status?: Database["public"]["Enums"]["return_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          customer_id?: string
          iban?: string | null
          id?: string
          order_id?: string
          product_state?: Database["public"]["Enums"]["return_product_state"]
          reason?: string | null
          resolution?: Database["public"]["Enums"]["return_resolution"]
          return_number?: string
          status?: Database["public"]["Enums"]["return_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "returns_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "returns_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      variants: {
        Row: {
          id: string
          price_cents: number
          product_id: string
          size_ml: number
        }
        Insert: {
          id?: string
          price_cents: number
          product_id: string
          size_ml: number
        }
        Update: {
          id?: string
          price_cents?: number
          product_id?: string
          size_ml?: number
        }
        Relationships: [
          {
            foreignKeyName: "variants_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      collections: {
        Row: {
          id: string
          slug: string
          name: string
          description: string | null
          hero_image: string | null
          active: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string | null
          hero_image?: string | null
          active?: boolean
          sort_order?: number
        }
        Update: {
          slug?: string
          name?: string
          description?: string | null
          hero_image?: string | null
          active?: boolean
          sort_order?: number
        }
        Relationships: []
      }
      collection_products: {
        Row: {
          collection_id: string
          product_id: string
          sort_order: number
        }
        Insert: {
          collection_id: string
          product_id: string
          sort_order?: number
        }
        Update: {
          collection_id?: string
          product_id?: string
          sort_order?: number
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      create_order: {
        Args: {
          p_billing: Json
          p_customer_id: string
          p_discount_cents: number
          p_guest_email: string
          p_idempotency_key: string
          p_items: Json
          p_payment_method: Database["public"]["Enums"]["pay_method_t"]
          p_shipping: Json
          p_shipping_cents: number
          p_shipping_method: Database["public"]["Enums"]["ship_method_t"]
          p_subtotal_cents: number
          p_total_cents: number
        }
        Returns: { id: string; order_number: string }[]
      }
      next_return_number: { Args: { p_year: number }; Returns: string }
      decrement_stock_for_order: {
        Args: { p_order_id: string }
        Returns: undefined
      }
      restore_stock_for_order: {
        Args: { p_order_id: string }
        Returns: undefined
      }
      is_admin: { Args: Record<string, never>; Returns: boolean }
    }
    Enums: {
      address_kind_t: "shipping" | "billing"
      bill_type_t: "fizica" | "juridica"
      bottle_color_t: "white" | "red" | "rose"
      gama_t: "cuvinte" | "semne" | "pauze"
      order_status_t:
        | "pending_payment"
        | "paid"
        | "shipped"
        | "delivered"
        | "cancelled"
        | "refunded"
      pay_method_t: "card-online" | "card-livrare" | "ramburs"
      pay_status_t:
        | "pending"
        | "succeeded"
        | "failed"
        | "refunded"
        | "partial_refund"
      return_product_state: "sigilat" | "deteriorat" | "neconform"
      return_resolution: "rambursare" | "inlocuire" | "voucher"
      return_status:
        | "pending"
        | "approved"
        | "in_transit"
        | "completed"
        | "rejected"
      ship_method_t: "curier" | "ridicare"
      sweetness_t: "sec" | "demisec" | "dulce"
      wine_type_t: "alb" | "rosu" | "rose"
    }
    CompositeTypes: { [_ in never]: never }
  }
}
